FROM quay.io/fedora/fedora-coreos:next as kernel-query
RUN rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}' > ./kernel-version.txt

FROM fedora:37 as builder
COPY --from=kernel-query /kernel-version.txt /kernel-version.txt
RUN cd /etc/yum.repos.d && curl -L -O https://src.fedoraproject.org/rpms/fedora-repos/raw/f37/f/fedora-updates-archive.repo &&\
    sed -i 's/enabled=AUTO_VALUE/enabled=true/' fedora-updates-archive.repo
#We can't use the `uname -r` as it will pick up the host kernel version 
RUN dnf install -y kernel-$(cat ./kernel-version.txt)
RUN sudo dnf groupinstall -y "Development Tools"
RUN dnf install -y automake libtool autoconf libblkid-devel libtirpc-devel libuuid-devel kernel-modules-$(cat ./kernel-version.txt) kernel-devel-$(cat ./kernel-version.txt)
RUN curl -L -O https://github.com/openzfs/zfs/releases/download/zfs-2.1.6/zfs-2.1.6.tar.gz && tar xzf zfs-2.1.6.tar.gz
RUN cd zfs-2.1.6 && sh autogen.sh && ./configure && make -s -j$(nproc)

FROM quay.io/fedora/fedora-coreos:next
#TODO check same kernel as builder
RUN rpm-ostree install make \
    #&& rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}' > ./kernel-version.txt && \
    #rpm-ostree install kernel-modules-$(cat ./kernel-version.txt) kernel-devel-$(cat ./kernel-version.txt) 
    && rpm-ostree cleanup -m && ostree container commit
COPY --from=builder /zfs-2.1.6 /zfs-2.1.6
RUN cd zfs-2.1.6 && sudo make install && sudo ldconfig
