# This example builds the zfs module following the work done at:
# https://github.com/skateman/atomic-zfs
FROM quay.io/fedora/fedora-coreos:stable

#We can't use the `uname -r` as it will pick up the host kernel version 
RUN rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}' > ./kernel-version.txt

RUN rpm-ostree install https://zfsonlinux.org/fedora/zfs-release$(rpm -E %dist).noarch.rpm && \
    rpm-ostree install flex bison diffutils dkms gcc make perl kernel-modules-$(cat ./kernel-version.txt) kernel-devel-$(cat ./kernel-version.txt) \
    && rpm-ostree cleanup -m && ostree container commit

RUN rpm-ostree install zfs-dkms && rpm-ostree cleanup -m && ostree container commit
